import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  safelist: [
    // DB-driven shop preview classes
    "bg-gradient-to-r",
    "bg-gradient-to-br",
    "bg-clip-text",
    "text-transparent",
    "text-emerald-400",
    "text-red-400",
    "text-sky-300",
    "from-blue-400",
    "to-cyan-400",
    "from-orange-400",
    "to-pink-500",
    "from-green-400",
    "via-teal-400",
    "from-purple-400",
    "to-violet-500",
    "from-red-500",
    "via-orange-400",
    "to-yellow-400",
    "from-yellow-300",
    "to-amber-500",
    "from-red-400",
    "via-yellow-400",
    "via-green-400",
    "via-blue-400",
    "from-emerald-950",
    "via-green-900",
    "to-teal-900",
    "from-cyan-950",
    "via-blue-900",
    "to-slate-900",
    "from-red-950",
    "via-rose-900",
    "from-indigo-950",
    "via-purple-900",
    "from-blue-950",
    "via-indigo-950",
    "to-slate-950",
    "from-orange-900",
    "to-purple-900",
    "from-pink-950",
    "to-fuchsia-950",
    "from-amber-950",
    "via-yellow-900",
    "to-orange-950",
    "from-fuchsia-950",
    "via-violet-900",
    "from-gray-950",
    "via-zinc-950",
    "to-black",
    "ring-2",
    "ring-[3px]",
    "ring-pink-400",
    "ring-pink-300",
    "ring-blue-300",
    "ring-slate-300",
    "ring-yellow-400",
    "ring-emerald-400",
    "ring-cyan-400",
    "ring-orange-500",
    "ring-violet-500",
    "shadow-[0_0_8px_rgba(244,114,182,0.4)]",
    "shadow-[0_0_8px_rgba(249,168,212,0.4)]",
    "shadow-[0_0_8px_rgba(203,213,225,0.4)]",
    "shadow-[0_0_10px_rgba(52,211,153,0.5)]",
    "shadow-[0_0_12px_rgba(34,211,238,0.6)]",
    "shadow-[0_0_14px_rgba(249,115,22,0.6)]",
    "shadow-[0_0_16px_rgba(139,92,246,0.7)]",
    "shadow-[0_0_16px_rgba(249,115,22,0.7)]",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["DM Sans", "sans-serif"],
        display: ["Outfit", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        aura: {
          glow: "hsl(var(--aura-glow))",
          mist: "hsl(var(--aura-mist))",
          rose: "hsl(var(--aura-rose))",
          mint: "hsl(var(--aura-mint))",
          lavender: "hsl(var(--aura-lavender))",
          sky: "hsl(var(--aura-sky))",
          gold: "hsl(var(--aura-gold))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "0.8" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "float": "float 3s ease-in-out infinite",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
